## this is a markdown file for correlation matrix plot ##

#http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software


##++++++++++++++++++++++++++++
#flattenCorrMatrix
#++++++++++++++++++++++++++++
#cormat : matrix of the correlation coefficients
#pmat : matrix of the correlation p-values

```{r}
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}
```



**Example of usage**
```
library(Hmisc)
res2<-rcorr(as.matrix(mtcars[,1:7]))
flattenCorrMatrix(res2$r, res2$P)

```
#output
#row column         cor            p
#1   mpg    cyl -0.85216194 6.112697e-10
#2   mpg   disp -0.84755135 9.380354e-10


**visulization**

#symnum() function
```{r}


```




#Use corrplot() function: Draw a correlogram
```{r}
install.packages("corrplot")

```


#Use chart.Correlation(): Draw scatter plots
```{r}
install.packages("PerformanceAnalytics")
library("PerformanceAnalytics")


```


#Use heatmap()
```{r}


```


#online tools
http://www.sthda.com/english/rsthda/correlation-matrix.php
